site_name: Cookiecutter Ai Flock
site_url: "https://llmslab.github.io/cookiecutter-ai-flock/"
repo_url: "https://github.com/LLMsLab/cookiecutter-ai-flock"
repo_name: llmslab.github.io/ccookiecutter-genai-ml-ai/
edit_uri: edit/main/docs/

theme:
  name: "material" #readthedocs
  logo: assets/logo.png
  icon:
    repo: simple/github
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: "slate"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: "default"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - content.code.annotate
extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/LLMsLab/cookiecutter-ai-flock"

markdown_extensions:
  # Include admonitions https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - abbr
  - footnotes
  - toc:
      permalink: true
      title: On this page
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - mkdocstrings
  - mermaid2
  - glightbox
  - git-revision-date-localized:
      fallback_to_build_date: true

extra_javascript:
  - https://fonts.googleapis.com/icon?family=Material+Icons
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
# Custom admonitions
extra_css:
  - stylesheets/extra.css
  - assets/css/custom.css

nav:
  - Home: index.md
  - Tutorials:
      - TOC: tutorials/toc-tutorials.md
      - Black Formatter: tutorials/black-formatter.md
      - Ruff Linter: tutorials/ruff-linter.md
      - Poetry Package Management: tutorials/poetry.md
      - MkDocs Documentation: tutorials/mkdocs-docs.md
      - Hydra Configuration: tutorials/hydra-config.md
      - Gitignore File Creation: tutorials/gitignore.md
      - Managing Data: tutorials/data.md
      - Data Version Control: tutorials/data-version-control.md
      - DVC Local Workflow: tutorials/dvc-local.md
      - DVC Cloud Storage: tutorials/dvc-cloud.md
      - DVC for Collaboration: tutorials/dvc-collaboration.md
      - Naming Conventions Tutorial: tutorials/naming-conventions.md
      - Windows OS Setup: tutorials/windows-os-setup.md
      - Markdown Documentation for ML Models: tutorials/markdown-ml-model-documentation.md
  - How-To Guides:
      - TOC: how-to-guides/toc-how-to-guides.md
      - DVC Setup: how-to-guides/dvc-set-up.md
      - DVC Communication: how-to-guides/dvc-communication.md
      - DVC VS Code Extension: how-to-guides/dvc-vscode-extension.md
      - Offline Cookiecutter Setup: how-to-guides/offline-cookiecutter-setup.md
      - Git Branch Naming Standards: how-to-guides/git-branch-naming-standards.md
      - Commit Message Standards in ML Projects: how-to-guides/commit-message-standards-ml.md
      - ML Data Folder Naming Guide: how-to-guides/ml-data-folder-naming.md
      - Data Files Naming Conventions: how-to-guides/ml-data-naming-conventions.md
      - Automating Metadata Creation: how-to-guides/machine-learning-metadata-automation.md
      - Enforcing Naming Conventions with GitHub Actions: how-to-guides/github-actions-naming-convention.md
  - Explanation:
      - TOC: explanation/toc-explanation.md
      - Understanding DVC: explanation/dvc-understanding-dvs.md
      - Git Branches in DVC: explanation/dvc-git-branches.md
      - Effective GitHub Naming Conventions: explanation/github-naming-conventions.md
      - Notebook and Script Naming Conventions in ML Projects: explanation/ml-naming-conventions.md
      - Model Persistence File Naming Conventions: explanation/model-persistence-naming-conventions.md
      - Introduction to Naming Conventions for AI Project Assets: explanation/naming-conventions.md
  - API Reference:
      - TOC: api-reference/toc-api-reference.md

