name: Ruff Linter

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Ruff
      run: pip install ruff

    - name: Check code with Ruff
      run: ruff check --preview src/ notebooks/


    - name: Fail if linting errors are detected
      run: |
        if ruff check --preview src/ notebooks/
          --quiet | grep -q 'error'; then
          echo "Linting errors detected. Please lint your code locally with Ruff and resolve all issues before pushing."
          exit 1
        else
          echo "No linting errors detected."
        fi